CREATE DATABASE IF NOT EXISTS `proxify`;

USE `proxify`;

CREATE TABLE IF NOT EXISTS `tasks`
(
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `url` VARCHAR(255) NOT NULL,
    `status` VARCHAR(255) NOT NULL DEFAULT 'NEW',
    `http_code` SMALLINT UNSIGNED
) ENGINE=InnoDB DEFAULT CHARSET=utf8;