#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Proxify\DistributedWorker\WorkerCommand;
use Proxify\DistributedWorker\DistributorCommand;

$application = new Application();

$application->add(new WorkerCommand());
$application->add(new DistributorCommand());

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$application->run();
